#!/bin/bash

SCEPTRE_SUCCESS="$HOME/Downloads/assets/war3_jobdone.mp3"
SCEPTRE_UPGRADE_STACK="$HOME/Downloads/assets/war3_jobdone.mp3"
SCEPTRE_FAIL="$HOME/Downloads/assets/war3_jobfail.wav"
SCEPTRE_INIT="$HOME/Downloads/assets/war3_workwork.mp3"
MISSINGARGS="$HOME/Downloads/assets/war3_missingargs.wav"
TRAPC="$HOME/Downloads/assets/war3_trapc.wav"
ARGTOTAL=3
SCEPTRE_HIJACK=$(which sceptre)

SCEPTRE_ACTION=$1
SCEPTRE_ENV=$2
SCEPTRE_STACK=$3
CHANGE_SET=$4

while getopts 'ztp' flag; do
  case "${flag}" in
    z)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$HOME/Downloads/assets/star_z_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$HOME/Downloads/assets/star_z_jobdelete.wav"
		SCEPTRE_SUCCESS="$HOME/Downloads/assets/star_z_jobdone.wav"
		SCEPTRE_FAIL="$HOME/Downloads/assets/star_z_jobfail.wav"
		SCEPTRE_INIT="$HOME/Downloads/assets/star_z_jobinit.wav"
		MISSINGARGS="$HOME/Downloads/assets/star_z_missingargs.wav"
		TRAPC="$HOME/Downloads/assets/star_z_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    t)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$HOME/Downloads/assets/star_t_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$HOME/Downloads/assets/star_t_jobdelete.wav"
		SCEPTRE_SUCCESS="$HOME/Downloads/assets/star_t_jobdone.wav"
		SCEPTRE_FAIL="$HOME/Downloads/assets/star_t_jobfail.wav"
		SCEPTRE_INIT="$HOME/Downloads/assets/star_t_jobinit.wav"
		MISSINGARGS="$HOME/Downloads/assets/star_t_missingargs.wav"
		TRAPC="$HOME/Downloads/assets/star_t_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    p)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$HOME/Downloads/assets/star_p_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$HOME/Downloads/assets/star_p_jobdelete.wav"
		SCEPTRE_SUCCESS="$HOME/Downloads/assets/star_p_jobdone.wav"
		SCEPTRE_FAIL="$HOME/Downloads/assets/star_p_jobfail.wav"
		SCEPTRE_INIT="$HOME/Downloads/assets/star_p_jobinit.wav"
		MISSINGARGS="$HOME/Downloads/assets/star_p_missingargs.wav"
		TRAPC="$HOME/Downloads/assets/star_p_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    *)
		exit 1
		;;
  esac
done

trap trapctrlc SIGINT
trapctrlc() {
	mplayer -quiet "$TRAPC" > /dev/null 2>&1
	echo -e '\033[1;33m'"$USER has left the game" '\033[0m'
	exit 1
}

if [[ "$SCEPTRE_ACTION" == "create-change-set" || "$SCEPTRE_ACTION" == "describe-change-set" ]]
then
	ARGTOTAL=$((ARGTOTAL + 1))
	mplayer -quiet "$SCEPTRE_INIT" > /dev/null 2>&1

	if "$SCEPTRE_HIJACK" "$SCEPTRE_ACTION" "$SCEPTRE_ENV" "$SCEPTRE_STACK" "$CHANGE_SET";
	then
		mplayer -quiet "$SCEPTRE_SUCCESS" > /dev/null 2>&1
		exit 0
	else
		mplayer -quiet "$SCEPTRE_FAIL" > /dev/null 2>&1
		exit 1
	fi

fi

if [[ $# -ne "$ARGTOTAL" ]];
then
	echo "Missing/too many parameters"
	mplayer -quiet "$MISSINGARGS" > /dev/null 2>&1
	exit 1
fi

case $SCEPTRE_ACTION in
	update-stack|update-stack-cs)
		SCEPTRE_SUCCESS=$SCEPTRE_UPGRADE_STACK
		CHANGE_SET=""
		;;
	delete-stack)
		SCEPTRE_INIT=$SCEPTRE_DELETE_STACK
		;;
esac


mplayer -quiet "$SCEPTRE_INIT" > /dev/null 2>&1
if "$SCEPTRE_HIJACK" "$SCEPTRE_ACTION" "$SCEPTRE_ENV" "$SCEPTRE_STACK";
then
	mplayer -quiet "$SCEPTRE_SUCCESS" > /dev/null 2>&1
else
	mplayer -quiet "$SCEPTRE_FAIL" > /dev/null 2>&1
	exit 1
fi

