#!/bin/bash

BASEDIR=$(cd "$(dirname "$(dirname "$(greadlink -f $0)")")" && pwd)

SCEPTRE_SUCCESS="$BASEDIR/assets/war3_jobdone.mp3"
SCEPTRE_UPGRADE_STACK="$BASEDIR/assets/war3_jobdone.mp3"
SCEPTRE_FAIL="$BASEDIR/assets/war3_jobfail.wav"
SCEPTRE_INIT="$BASEDIR/assets/war3_workwork.mp3"
MISSINGARGS="$BASEDIR/assets/war3_missingargs.wav"
TRAPC="$BASEDIR/assets/war3_trapc.wav"
ARGTOTAL=3
SCEPTRE_HIJACK=$(which sceptre)

AFPLAY_OPTS=( -v "${VOLUME:-0.2}" )

SCEPTRE_ACTION=$1
SCEPTRE_ENV=$2
SCEPTRE_STACK=$3
CHANGE_SET=$4

while getopts 'ztp' flag; do
  case "${flag}" in
    z)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$BASEDIR/assets/star_z_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$BASEDIR/assets/star_z_jobdelete.wav"
		SCEPTRE_SUCCESS="$BASEDIR/assets/star_z_jobdone.wav"
		SCEPTRE_FAIL="$BASEDIR/assets/star_z_jobfail.wav"
		SCEPTRE_INIT="$BASEDIR/assets/star_z_jobinit.wav"
		MISSINGARGS="$BASEDIR/assets/star_z_missingargs.wav"
		TRAPC="$BASEDIR/assets/star_z_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    t)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$BASEDIR/assets/star_t_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$BASEDIR/assets/star_t_jobdelete.wav"
		SCEPTRE_SUCCESS="$BASEDIR/assets/star_t_jobdone.wav"
		SCEPTRE_FAIL="$BASEDIR/assets/star_t_jobfail.wav"
		SCEPTRE_INIT="$BASEDIR/assets/star_t_jobinit.wav"
		MISSINGARGS="$BASEDIR/assets/star_t_missingargs.wav"
		TRAPC="$BASEDIR/assets/star_t_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    p)
	    	ARGTOTAL=4
		SCEPTRE_UPGRADE_STACK="$BASEDIR/assets/star_p_jobupdate.wav"
		SCEPTRE_DELETE_STACK="$BASEDIR/assets/star_p_jobdelete.wav"
		SCEPTRE_SUCCESS="$BASEDIR/assets/star_p_jobdone.wav"
		SCEPTRE_FAIL="$BASEDIR/assets/star_p_jobfail.wav"
		SCEPTRE_INIT="$BASEDIR/assets/star_p_jobinit.wav"
		MISSINGARGS="$BASEDIR/assets/star_p_missingargs.wav"
		TRAPC="$BASEDIR/assets/star_p_trapc.wav"
		SCEPTRE_ACTION=$2
		SCEPTRE_ENV=$3
		SCEPTRE_STACK=$4
		CHANGE_SET=$5
		;;
    *)
		exit 1
		;;
  esac
done

trap trapctrlc SIGINT
trapctrlc() {
	afplay "${AFPLAY_OPTS[@]}" "$TRAPC"
	echo -e '\033[1;33m'"$USER has left the game" '\033[0m'
	exit 1
}

# if [[ "$SCEPTRE_ACTION" == "delete-env" || "$SCEPTRE_ACTION" == "describe-env" || "$SCEPTRE_ACTION" == "launch-env" ]]

REGEX="^.*-env$"
if [[ "$SCEPTRE_ACTION" =~ $REGEX ]]
then
	if [[ $SCEPTRE_ACTION == "delete-env" ]]
	then
		SCEPTRE_INIT=$SCEPTRE_DELETE_STACK
	fi

	afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_INIT"

	if "$SCEPTRE_HIJACK" "$SCEPTRE_ACTION" "$SCEPTRE_ENV";
	then
		afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_SUCCESS"
		exit 0
	else
		afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_FAIL"
		exit 1
	fi
fi

if [[ "$SCEPTRE_ACTION" == "create-change-set" || "$SCEPTRE_ACTION" == "describe-change-set" ]]
then
	ARGTOTAL=$((ARGTOTAL + 1))
	afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_INIT"

	if "$SCEPTRE_HIJACK" "$SCEPTRE_ACTION" "$SCEPTRE_ENV" "$SCEPTRE_STACK" "$CHANGE_SET";
	then
		afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_SUCCESS"
		exit 0
	else
		afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_FAIL"
		exit 1
	fi
fi


case $SCEPTRE_ACTION in
	update-stack|update-stack-cs)
		SCEPTRE_SUCCESS=$SCEPTRE_UPGRADE_STACK
		CHANGE_SET=""
		;;
	delete-stack)
		SCEPTRE_INIT=$SCEPTRE_DELETE_STACK
		;;
esac

if [[ $# -ne "$ARGTOTAL" ]];
then
	echo "Missing/too many parameters"
	afplay "${AFPLAY_OPTS[@]}" "$MISSINGARGS"
	exit 1
fi

afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_INIT"
if "$SCEPTRE_HIJACK" "$SCEPTRE_ACTION" "$SCEPTRE_ENV" "$SCEPTRE_STACK";
then
	afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_SUCCESS"
else
	afplay "${AFPLAY_OPTS[@]}" "$SCEPTRE_FAIL"
	exit 1
fi
